name: Feature Request
description: Suggest a new feature or enhancement for TideSignal
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible to help us understand your idea.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: "I'm always frustrated when... / It would be helpful to have..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: "Add a button that... / Display the information in..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: "I could work around this by... / Another approach might be..."
    validations:
      required: false

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: What part of the app does this relate to?
      options:
        - Main tide display
        - Station picker
        - Tile widget
        - Watch face complication
        - Settings
        - Data pipeline
        - Performance / Battery
        - Accessibility
        - Other (please specify in Additional Context)
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority (Your Opinion)
      description: How important is this feature to you?
      options:
        - Critical - I can't use the app without this
        - High - This would significantly improve my experience
        - Medium - Nice to have
        - Low - Minor enhancement
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how you would use this feature
      placeholder: "When I'm fishing, I need to quickly see... / While planning a trip, it would help to..."
    validations:
      required: false

  - type: textarea
    id: mockup
    attributes:
      label: Mockup / Visual
      description: If applicable, add sketches, mockups, or links to similar features in other apps
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information about the feature request
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing feature requests to avoid duplicates
          required: true
        - label: This feature aligns with TideSignal's focus on tide prediction
          required: false
        - label: I would be willing to contribute to implementing this feature
          required: false
